### PR TITLE
Get this up to speed

### PR DESCRIPTION
**Pull request by flying-sheep**
Hi, since this hasn’t seen an update in quite some time, I’d like to get it up to speed and working again.

### CODE REVIEW

**Comment by takluyver** [comment]
I rejected PR #5, so I'm a bit irritated that you seem to by trying to slip the same change past me as if it was just a general maintenance thing.

**Comment by takluyver** [comment]
I'm happy to update the imports and so forth for Jupyter, but I don't particularly care about applying a standardised code style.

**Comment by flying-sheep** [comment]
sorry, i didn’t provide all the details. new stuff:

* Actually works with new XSRF-enabled servers
* uic2.py can now rebuild the qrc files, the theme index, the OSX icon directory (now excluded from the repo) and the theme indices.
* theme indices? yes: it now installs its own in-memory icon theme to provide icons. autocaching by `QIcon.fromTheme` and automatically good icons included!
* PEP8-friendlier (indents and empty lines mainly)

**Comment by flying-sheep** [comment]
@takluyver still here? i think you missed my comment

**Comment by flying-sheep** [comment]
@takluyver undid the style changed. could you reopen this please?

**Comment by takluyver** [comment]
Sorry, may have jumped the gun. I've got it working for me on master; do you need anything else? Github isn't letting me reopen it now:

screenshot from 2017-01-24 16-29-51

**Comment by flying-sheep** [comment]
OK, i’ll just file a new one 😄 if there’s anything that needs addressing, go right ahead!

you should know me better than to assume i’d try to sneak something past you though 😉

**Pull request closed without merging**
